  eureka:
    instance:
      hostname: localhost
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

  server:
    port: 8080
  spring:
    application:
      name: DEPARTMENT-SERVICE
    config:
      import: optional:configserver:http://localhost:8888
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/department_service
      username: root
      password: toortoor
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true

  application:
    config:
      employees-url: http://localhost:8090/api/v1/employee